#!/bin/bash -e
# This script is an example script showing how a full Raspbian image can be
# built and customized end-to-end. This script adds just a few things to the
# minimal install built by the build-raspbian script. It brings up the ethernet
# port with DHCP, allows domain names to be resolved, and installs a text
# editor. It is expected that the end-user of this library will modify this
# script to create custom images. It is even possible to make multiple images
# by calling the build-image script multiple times with different image names
# after re-customizing. That could be useful for creating a cluster of
# raspberry pis each with hardcoded static IPs.

CHROOT="${RASPBIAN_REMASTER_CHROOT:-./raspbian}"
IMAGE="${RASPBIAN_REMASTER_IMAGE:-./images/raspbian.img}"
"$(dirname "${BASH_SOURCE[0]}")"/build-raspbian "${CHROOT}"

chroot "${CHROOT}" apt-get install -y dhcpcd5 openresolv vim

# Set eth0 to use DHCP.
cat << EOF > "${CHROOT}/etc/network/interfaces.d/eth0"
allow-hotplug eth0
iface eth0 inet dhcp
EOF

# Set the root password. This is obviously not secure. Real customization
# scripts should override this, or use 
chroot "${CHROOT}" /bin/bash -c "echo \"root:raspberry\" | chpasswd"

"$(dirname "${BASH_SOURCE[0]}")"/build-image "${CHROOT}" "${IMAGE}"
