#!/bin/bash -e
# This script contains common code shared between the various build scripts.

# All of the build scripts must run as root, so just check that here.
[[ $EUID -ne 0 ]] && echo "This tool must be run as root!" && exit 1

CHROOT=${RASPBIAN_REMASTER_CHROOT:-./raspbian}
PUBLISH=${RASPBIAN_REMASTER_PUBLISH:-./images}

function chroot_cmd {
  mkdir -p ${CHROOT}/{proc,sys,dev/pts}
  mount | grep -q ${CHROOT}/proc || mount -t proc none ${CHROOT}/proc
  mount | grep -q ${CHROOT}/sys || mount -t sysfs none ${CHROOT}/sys
  mount | grep -q ${CHROOT}/dev || mount -o bind /dev ${CHROOT}/dev
  mount | grep -q ${CHROOT}/dev/pts || mount -o bind /dev/pts ${CHROOT}/dev/pts
  chroot ${CHROOT} "$@"
}
